# mamba env update -n vectorrx -f "environment.yml"
name: vectorrx
channels:
- conda-forge
dependencies:
- faiss-cpu=1.7.4
- gcsfs=2024.2.0
- openai=1.13.3
- pandas=1.5.3
- pip=24.0
- python=3.10.13
- streamlit=1.32.1
- pip:
  - st-files-connection