# mamba env update -n vectorrx -f "environment_aarch64.yml"
name: vectorrx
channels:
- conda-forge
dependencies:
- faiss-cpu=1.7.4
- google-auth=2.29.0
- google-cloud-storage=2.16.0
- openai=1.13.3
- numpy==1.26.4
- pandas==2.2.1
- plotly=5.19.0
- python=3.11.8
- scikit-learn=1.3.0
- streamlit=1.32.2
